language: objective-c

osx_image: xcode9.1

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.sbt
  - platform
  - apps

install:
  - bin/prelude.sh

script:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "skip travis" && exit 0 ; fi
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[travis skip]" ; then echo "travis skip" && exit 0 ; fi
  - unset JVM_OPTS
  - unset SBT_OPTS
  - bin/sbt-launch.sh clean test:compile test:fastOptJS
  - bin/sbt-launch.sh 'project sireum-jvm' test
